### ISSUE TITLE
[Question] Complete DE

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#23]
@fichtner Do you want to help to complete the last strings in DE?
Today less than 150 are left.

**Comment by fabianfrz** [comment]
97% done

**Comment by fichtner** [comment]
I did about 500 words. But we can reach 100% for 17.1.5 :)

**Comment by fabianfrz** [comment]
No we cannot, there are still broken strings left (for example containing HTML or make no sense) but 99% is possible.

**Comment by fichtner** [comment]
There will always be. Translations are best efforts. Errors are curated and properly emulated for a 100% translation experience ;)

**Comment by fichtner** [comment]
That being said, the good thing about such errors is that even though we translate to live with them for now they get purged from the templates when we fix them in the code and can properly redo the translations then.

**Comment by fabianfrz** [comment]
looks like we have completed 99%. 94 Strings left.

**Comment by fabianfrz** [comment]
75 left

**Comment by fichtner** [comment]
65

**Comment by fabianfrz** [comment]
48

**Comment by fabianfrz** [comment]
32 @DokuKaefer contributed some ;)

**Comment by fabianfrz** [comment]
25 left. @fichtner the last strings are for you.

**Comment by fichtner** [comment]
7 are still open, stupidly complicated DCHP explanations...

**Comment by fichtner** [comment]
done :)

**Comment by fabianfrz** [comment]
@fichtner toll, danke - dann kann das nächste update kommen, bei dem dan die ganzen neuen plugins drin sind ;)

sind eh nur mehr ein paar monate...

**Comment by fabianfrz** [comment]
heißt gleichzeitig mehr zeit für plugins
