### ISSUE TITLE
Template renewal

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#24]
@fichtner there is nealy no progress on pootle, so can you renew the pot file as we are going to reach 17.7 soon?

**Comment by fichtner** [comment]
there will be one more update with 17.1.8 and then we are stopping translation efforts for 17.1 to focus on 17.7, yup.

**Comment by fichtner** [comment]
@fabianfrz last update went out, so we can start on this... but already found an issue with quagga:

lang._("text") doesn't work relibably in Phalcon, so we need to transform it to lang._('text')

**Comment by fabianfrz** [comment]
@fichtner created a PR: https://github.com/opnsense/plugins/pull/169

**Comment by fabianfrz** [comment]
there is one too in `security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt`. @fraenki it's yours.

**Comment by fichtner** [comment]
This won't fix for acme-client. We can't even escape in phalcon...

**Comment by fabianfrz** [comment]
@fichtner Is there progress on this one?

**Comment by fraenki** [comment]
@fichtner @fabianfrz Guys, I know I'm late to the party... so let me only ask this question: the issue in `security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt` can't be fixed, right?

**Comment by fichtner** [comment]
correct, need to coordinate with phalcon

**Comment by fabianfrz** [comment]
@fichtner the new template should be compiled as there is only around one month left until `17.7` should be released so we should start it to keep it at 100% with the final release.

**Comment by fichtner** [comment]
all in good time! we've gained almost 500 strings, I don't know how the bounce rate is yet. Will schedule Pootle downtime for Sunday-Monday to merge the progress so work can start.

**Comment by fichtner** [comment]
@fabianfrz @fraenki I added an upstream ticket https://github.com/phalcon/cphalcon/issues/12888

**Comment by fabianfrz** [comment]
Good to know. It may be fixed some day - BTW: got translation to 93% already

**Comment by fabianfrz** [comment]
And we are on 94% now.

**Comment by fabianfrz** [comment]
@fichtner I'll let you do the rest of the german translation (around 300 worlds left :) )
