### ISSUE TITLE
Template renewal

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#28]
@fichtner it might be a good idea to update the templates as there have been some plugins added since. At least:

* mdns-repeater
* c-icap
* clamav

Those plugins are currently missing in the translation files.

**Comment by fichtner** [comment]
Pootle has been updated and the final update for 17.7 wasn't done so yes. But keep in mind we can't do this more than once early into 17.7.x, because this ultimately removes progress from the 17.7 translation.

**Comment by fabianfrz** [comment]
As far as I know there are not many changes which would break old translations. Also pootle shows that nobody is working on them.
