### ISSUE TITLE
pkg: No packages available to install matching 'p5-Locale-Maketext-Lexicon' 

### ISSUE THREAD

**Issue by Stephanowicz** [opnsense/lang#30]
Hi,

just wanted to test some updates in the _de_DE.po_ file and followed the instructions in the _README.md_ but can't install the **p5-Locale-Maketext-Lexicon**

Error:
> pkg: No packages available to install matching 'p5-Locale-Maketext-Lexicon' have been found in the repositories

Cheers, Stephan

**Comment by fichtner** [comment]
Not sure what's going on there, but in any case translations are done via https://translate.opnsense.org/ -- please drop us a line at project@opnsense.org with your preferred username and we will send out an account

**Comment by fichtner** [comment]
PS: are you trying to install this from OPNsense or FreeBSD? OPNsense?

**Comment by Stephanowicz** [comment]
yep - from opnSense

**Comment by fichtner** [comment]
ok...it only works from the FreeBSD build host, maybe that should be mentioned as well

**Comment by fichtner** [comment]
or we add the package... either way solvable 👍

**Comment by Stephanowicz** [comment]
Ok, this translation site - is there a way just to test some changes?

**Comment by fichtner** [comment]
you only need gettext-tools installed. edit de_DE.po, then run "make install"

**Comment by fichtner** [comment]
oh and possibly "configctl webgui restart"

**Comment by Stephanowicz** [comment]
Thanx - It's working!

**Comment by fichtner** [comment]
Fixed via https://github.com/opnsense/tools/commit/5fe2708f5edc63dac0455427cd0d1fdd2d3f3d5b
