### ISSUE TITLE
18.1: Template Refresh

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#32]
The new release is coming and translation progress may begin soon ;)

**Comment by fabianfrz** [comment]
@fichtner ping

**Comment by fichtner** [comment]
nope, not yet

**Comment by fabianfrz** [comment]
now?

**Comment by fichtner** [comment]
as soon as somebody spends a whole day repairing pootle

**Comment by taguchi-ch** [comment]
When will come the day?

**Comment by fichtner** [comment]
The translations server is currently in need of maintenance as it loses new translations strings and shows 100% completed where it shouldn't. We need to redo, but that isn't easy and now we have decided to get 18.1 out first and circle back to the translations. Sorry! :(

**Comment by fichtner** [comment]
done, need to reset pootle project to allow all new translations to be seen. will hopefully happen in the next 1-2 days. previously finished translations are roughly at 70%, a lot of new strings have been added.
