### ISSUE TITLE
New translation: Malaysian (Bahasa Melayu)

### ISSUE THREAD

**Issue by nekoprog** [opnsense/lang#50]
Hi, I would like to contribute to Malaysian (Bahasa Melayu) translation, hope you can add new language on https://translate.opnsense.org/ so that I can join the translation team. :)

**Comment by fichtner** [comment]
I'm not an expert. For selection there's "Malay" and "Malay (BN)". BN is fur Brunei? We need the normal one?

**Comment by nekoprog** [comment]
I guess Malay (BN) is for Brunei. Just normal Malay for Malaysia.

**Comment by fichtner** [comment]
Ok, done :)

**Comment by nekoprog** [comment]
Thanks a lot
