### ISSUE TITLE
Vietnamese language

### ISSUE THREAD

**Issue by saphire7** [opnsense/lang#53]
I would like to contribute mini Vietnamese language project. I was creating vn_VN.po from original en_US. Hope receive approval from OPN Sense founders and all contributors.

Thank you All.

**Comment by AdSchellevis** [comment]
best create an account on POEditor (https://poeditor.com/join/project/JErIQiUPQa) ad drop us an email (project at opnsense.org) if your language isn't there yet.

**Comment by saphire7** [comment]
Thank you for adding my language!

**Comment by fichtner** [comment]
Do you need German as well? It is quite a job to do one language alone and German is pretty well covered already :)

**Comment by saphire7** [comment]
> Do you need German as well? It is quite a job to do one language alone and German is pretty well covered already :)

No, thank you!

**Comment by fichtner** [comment]
Ok, good luck and let me know if I can help out with something. 👍
