### ISSUE TITLE
maltrail: wrong translation (german)

### ISSUE THREAD

**Issue by ramon-kramer-flashtec** [opnsense/lang#58]
The translation for maltrail should not be mailtrail as it doesn't mean mail :)

menu screenshot:

![grafik](https://user-images.githubusercontent.com/45063643/161027267-dcc80804-05f8-4531-ab33-4d41c68e056e.png)

in translation file de_DE.po
```
msgid "Maltrail"
msgstr "Mailtrail"
```
should be
```
msgid "Maltrail"
msgstr "Maltrail"
```

**Comment by fichtner** [comment]
Thanks, actually I removed the translation over at translate.opnsense.org as it doesn't bring any advantages or further mistranslation ;)
