### ISSUE TITLE
Merge of the current translation progress

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#6]
@fichtner The translation files should be updated with the next release.

Maybe also the template could be updated as well.

**Comment by fichtner** [comment]
soooooooo much work ;(

**Comment by fichtner** [comment]
16% "lost in translation" from 16.1 to 16.7

New rule: we'll only ever regenerate and merge during release candidate phase, which is usually the last month of each series.

**Comment by fichtner** [comment]
@fabianfrz ok, not entirely true as there were some string additions but still quite a bit of churn :)

**Comment by fabianfrz** [comment]
If you use my translation patches in stable they will make the translations unavailable too as the string usually changes and cannot be found in the translation database :(

**Comment by fichtner** [comment]
If I don't use them it makes patch review for releases too hard, so I think that's ok... We get new translations through opnsense-lang updates, but lose some for backporting development progress.
