### ISSUE TITLE
Spelling mistake in the en_US translation

### ISSUE THREAD

**Issue by arrys** [opnsense/lang#64]
I believe there is a spelling mistake on [line 8432 in en_US.pot](https://github.com/opnsense/lang/blob/9e5f875304389168ee35a87ecf831dde8717a36d/en_US.pot#L8432).

The "cdir" should be "cidr".

**Comment by fichtner** [comment]
Thanks, fixed via https://github.com/opnsense/plugins/commit/3d4c6735

The en_US file will be regenerated later
