### ISSUE TITLE
translate.opnsense.org: This project can't accept new contributors at this time. Please try again later.

### ISSUE THREAD

**Issue by matsimon** [opnsense/lang#65]
The readme indicates that you should contribute translation updates using the service provided by poeditor.com, however after registering, and then attempting to join the project I get:

``This project can't accept new contributors at this time. Please try again later.``

Is this still the right / expected way to contribute translations or have things changed?

BTW, this error is the reason for PR #66.

**Comment by fichtner** [comment]
Hey, long time no see! hope you are doing good?

Not sure, first time I heard about Poeditor doing this, but they also said they wanted to restructure a little on their end (and it slightly affects open source projects like us). Let me see if I can make sense of this.


Cheers,
Franco

**Comment by matsimon** [comment]
I have been using OPNsense for some time both personally and for work, didn't think you'd remember me, cool. 😄

It seems that the Free Tier is limited to 5 contributors, on the regular side it's only the next paid level "Start" that gets unlimited contributors based in that table here: https://poeditor.com/pricing/ - maybe that's the current Tier the OPNsense translations are currently stuck on.

They seem to continue supporting OSS projects under a OSI-compliant license, I imagine you'd have to apply for it (again)?
See: https://poeditor.com/kb/open-source-localization

Hope it goes well since manually editing .po files is definitely less inviting to casual translators.

**Comment by fichtner** [comment]
I sent them a mail now... things have been a bit wild on my end.


Cheers,
Franco

**Comment by fichtner** [comment]
@matsimon should be fixed... can you try to register again and close if it works?

**Comment by matsimon** [comment]
Hi Franco

It looks I'm getting a step further than when I reported the issue, cool: I can now join the OPNsense translation project and have requested to join the German translation. It seems it that requires an approval on the project owners' end on a per language basis (that one might actually be desired). Can you approve me? If I can actually do a translation I'll close the issue asap.

**Comment by fichtner** [comment]
Hi Mathieu,

Yep, the approval is the usual step. We need to be a bit cautious about that process.

I approved you for both languages.


Cheers,
Franco

**Comment by matsimon** [comment]
Cool, thank you for jumping through the hoop,s I can now confirm that I can access these translation!
