### ISSUE TITLE
Extraction of strings in volt-templates may be broken 

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/lang#7]
It does not work, when a string uses format to add the html contents.

see https://translate.opnsense.org/de/gui/translate/de.po#unit=76267

**Comment by fichtner** [comment]
The Regex has another problem with not ignoring escaped single quotes, although the termination sequence makes it pretty robust as long as the spacing around it is correct, (' and ') that is.

Translations have not been merged, we'll do this once again shortly after the last 16.1.x in preparation for the final 16.7 :)

Thanks for the report, keep up the good work!
